//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOES.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BalanceTbl
    {
        public int Id { get; set; }
        public Nullable<int> BalanceMonth { get; set; }
        public Nullable<int> BalanceYear { get; set; }
        public Nullable<int> BalanceAmount { get; set; }
    }
}
