//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOES.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class FeatureTbl
    {
        public int FeatureID { get; set; }
        public string FeatureText { get; set; }
        public Nullable<double> FeatureAmount { get; set; }
    }
}
