//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOES.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class InvoiceIDTbl
    {
        public int InvoiceKey { get; set; }
        public string InvoiceRoomID { get; set; }
        public string RoomID { get; set; }
        public Nullable<System.DateTime> InvoiceDate { get; set; }
    }
}
