//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOES.DAL.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class LOESEntities : DbContext
    {
        public LOESEntities()
            : base("name=LOESEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AmountTbl> AmountTbl { get; set; }
        public virtual DbSet<BalanceTbl> BalanceTbl { get; set; }
        public virtual DbSet<FeatureTbl> FeatureTbl { get; set; }
        public virtual DbSet<InvoiceIDTbl> InvoiceIDTbl { get; set; }
        public virtual DbSet<InvoiceTbl> InvoiceTbl { get; set; }
        public virtual DbSet<RoomAccountTbl> RoomAccountTbl { get; set; }
        public virtual DbSet<RoomCostTbl> RoomCostTbl { get; set; }
        public virtual DbSet<RoomerTbl> RoomerTbl { get; set; }
        public virtual DbSet<RoomTbl> RoomTbl { get; set; }
    }
}
