//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOES.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomTbl
    {
        public string RoomID { get; set; }
        public bool Active { get; set; }
        public Nullable<int> RoomerID { get; set; }
        public Nullable<int> AmountID { get; set; }
        public Nullable<int> Area { get; set; }
        public Nullable<double> Saldo { get; set; }
    }
}
