//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace LOES.DAL.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RoomAccountTbl
    {
        public int AccountID { get; set; }
        public string RoomerName { get; set; }
        public string RoomID { get; set; }
        public Nullable<int> EnterMonth { get; set; }
        public Nullable<int> EnterYear { get; set; }
        public Nullable<System.DateTime> EnterDate { get; set; }
        public Nullable<System.DateTime> PeriodStart { get; set; }
        public Nullable<System.DateTime> PeriodEnd { get; set; }
        public Nullable<int> AmountType { get; set; }
        public Nullable<double> Amount { get; set; }
        public Nullable<int> InvoiceIndex { get; set; }
    }
}
